name: Release Mod

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version and group from build.gradle
      id: extract_values
      run: echo "::set-output name=version::$(grep version build.gradle | awk -F"'" '{print $2}') ::set-output name=group::$(grep group build.gradle | awk -F"'" '{print $2}')"

    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build Mod
      run: ./gradlew build

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs/${{ steps.extract_values.outputs.group }}-${{ steps.extract_values.outputs.version }}.jar
        asset_name: your-mod-${{ steps.extract_values.outputs.version }}.jar
        asset_content_type: application/java-archive
