name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Get Version
      id: version
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let ref = '${{ github.ref }}';
          return ref.startsWith('refs/tags/v') ? ref.replace('refs/tags/v', '') : 'indev';
    - name: Get Version Type
      id: version_type
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let version = '${{ steps.version.outputs.result }}';
          return version.includes('alpha') ? 'alpha' : (version.includes('beta') ? 'beta' : 'release');
    - name: Log Version Info
      env:
        VERSION: ${{ steps.version.outputs.result }}
        VERSION_TYPE: ${{ steps.version_type.outputs.result }}
      run: echo "version = $VERSION, type = $VERSION_TYPE"
    - name: Build
      run: ./gradlew build
      env:
        VERSION: ${{ steps.version.outputs.result }}
    - name: Create release tag
      run: git tag -a v${{ steps.version.outputs.result }} -m "Release v${{ steps.version.outputs.result }}"
    - name: Push tags
      run: git push origin --tags
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: "TerraFirmaCraft 1.12.2-${{ steps.version.outputs.result }}"
        tag_name: "v${{ steps.version.outputs.result }}"
