name: Release Mod

on:
  release:
    types:
      - created
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version for the release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew

    - name: Build Mod
      run: ./gradlew build

    - name: Get PR Commits
      id: get_pr_commits
      run: |
        echo "Before: ${{ github.event.before }}"
        echo "After: ${{ github.sha }}"
        COMMITS=$(git log --pretty=format:'%s' ${{ github.event.before }}..${{ github.sha }})
        echo "Raw Commits: $(git log ${{ github.event.before }}..${{ github.sha }})"
        echo "PR Commits: $COMMITS"
        echo "##[set-output name=commits;]$COMMITS"

    - name: Display PR Commits
      run: echo "${{ steps.get_pr_commits.outputs.commits }}"

    - name: Create Release Tag
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs, 'version'))
      run: git tag -a v${{ steps.extract_values.outputs.version }} -m "Release v${{ steps.extract_values.outputs.version }}"

    - name: Push Release Tag
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs, 'version'))
      run: git push origin v${{ steps.extract_values.outputs.version }}

    - name: Create GitHub Release
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs, 'version'))
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/${{ steps.extract_values.outputs.group }}-${{ steps.extract_values.outputs.version }}.jar
        tag_name: v${{ steps.extract_values.outputs.version }}
        release_name: Release v${{ steps.extract_values.outputs.version }}
        body: ${{ steps.get_pr_commits.outputs.commits }}
