name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Get Version
      id: version
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let ref = '${{ github.ref }}';
          return ref.startsWith('refs/tags/v') ? ref.replace('refs/tags/v', '') : 'indev';
    - name: Get Version Type
      id: version_type
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          let versionValue = '${{ steps.version.outputs.result }}';
          return versionValue.includes('alpha') ? 'alpha' : (versionValue.includes('beta') ? 'beta' : 'release');
    - name: Log Version Info
      env:
        VERSION: ${{ steps.version.outputs.result }}
        VERSION_TYPE: ${{ steps.version_type.outputs.result }}
      run: echo "version = $VERSION, type = $VERSION_TYPE"
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        BUILD_VERSION: ${{ steps.version.outputs.result }}
        github-tag: ${{ github.ref }}
        github-draft: true
        github-prerelease: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: Visroom Powder 1.12.2-${{ steps.version.outputs.result }}
        version: ${{ steps.version.outputs.result }}
        version-type: ${{ steps.version_type.outputs.result }}
        java: 8
        loaders: |
          forge
        changelog-file: CHANGELOG.md
    - name: Create release tag
      uses: softprops/action-gh-release@v1
      with:
        files: 'build/libs/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
